/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.util.Random;

/**
 *
 * @author rafael
 */
public class Genio extends javax.swing.JFrame {

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalculaPalpite = new javax.swing.JButton();
        txtValorPalpite = new javax.swing.JSpinner();
        lblBalaoTextoGenio = new javax.swing.JLabel();
        lblImageGenio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCalculaPalpite.setText("Palpite");
        btnCalculaPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaPalpiteActionPerformed(evt);
            }
        });

        txtValorPalpite.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        lblBalaoTextoGenio.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblBalaoTextoGenio.setForeground(new java.awt.Color(23, 11, 11));
        lblBalaoTextoGenio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalaoTextoGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/balao.png"))); // NOI18N
        lblBalaoTextoGenio.setText("<html>  Vou pensar em um<br/>  valor entre <strong>1</strong> e <strong>5</strong>.<br/> Tente adivinhar.  </html>");
        lblBalaoTextoGenio.setToolTipText("");
        lblBalaoTextoGenio.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBalaoTextoGenio.setFocusTraversalPolicyProvider(true);
        lblBalaoTextoGenio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblImageGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/genio.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalaoTextoGenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCalculaPalpite, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addComponent(txtValorPalpite)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImageGenio)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblImageGenio))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(lblBalaoTextoGenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(txtValorPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculaPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculaPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaPalpiteActionPerformed
        // Função que verifica se o palpite do usuário é igual ao número sorteado.
        
        int palpite = Integer.parseInt(txtValorPalpite.getValue().toString());
        
        if (palpite == numeroSorteado) {
            lblBalaoTextoGenio.setText("<html><strong>ACERTOU!</strong></html>");
        } else {
            lblBalaoTextoGenio.setFont(new java.awt.Font("Ubuntu", 0, 20));
            lblBalaoTextoGenio.setText(
                String.format("<html><strong>ERROU! Eu<br/>pensei no valor %d</strong></html>", numeroSorteado)
            );
        }
    }//GEN-LAST:event_btnCalculaPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Genio().setVisible(true);
            }
        });
    }
    
    Random random = new Random();
    
    // Gera um número aleatório de 1 a 5.
    int numeroSorteado = random.ints(1, 6).findFirst().getAsInt();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculaPalpite;
    private javax.swing.JLabel lblBalaoTextoGenio;
    private javax.swing.JLabel lblImageGenio;
    private javax.swing.JSpinner txtValorPalpite;
    // End of variables declaration//GEN-END:variables
}
