/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author rafael
 */
public class SuperComputador extends javax.swing.JFrame {

    /**
     * Creates new form SuperComputador
     */
    public SuperComputador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInformarValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        lblRestoDivisao = new javax.swing.JLabel();
        lblRestoDivisaoResultado = new javax.swing.JLabel();
        lblElevadoAoCubo = new javax.swing.JLabel();
        lblRaizQuadrada = new javax.swing.JLabel();
        lblRaizQuadradaResultado = new javax.swing.JLabel();
        lblRaizCubica = new javax.swing.JLabel();
        lblRaizCubicaResultado = new javax.swing.JLabel();
        lblElevadoAoCuboResultado = new javax.swing.JLabel();
        lblValorAbsoluto = new javax.swing.JLabel();
        lblValorAbsolutoResultado = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblImageCalculadora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInformarValor.setText("Informe um valor:");

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fouroperations.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblRestoDivisao.setText("Resto da divisão por 2:");

        lblRestoDivisaoResultado.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblRestoDivisaoResultado.setForeground(new java.awt.Color(58, 64, 222));
        lblRestoDivisaoResultado.setText("0");

        lblElevadoAoCubo.setText("Elevado ao Cubo:");

        lblRaizQuadrada.setText("Raiz Quadrada:");

        lblRaizQuadradaResultado.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblRaizQuadradaResultado.setForeground(new java.awt.Color(58, 64, 222));
        lblRaizQuadradaResultado.setText("0");

        lblRaizCubica.setText("Raiz Cúbica:");

        lblRaizCubicaResultado.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblRaizCubicaResultado.setForeground(new java.awt.Color(58, 64, 222));
        lblRaizCubicaResultado.setText("0");

        lblElevadoAoCuboResultado.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblElevadoAoCuboResultado.setForeground(new java.awt.Color(58, 64, 222));
        lblElevadoAoCuboResultado.setText("0");

        lblValorAbsoluto.setText("Valor Absoluto:");

        lblValorAbsolutoResultado.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblValorAbsolutoResultado.setForeground(new java.awt.Color(58, 64, 222));
        lblValorAbsolutoResultado.setText("0");

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTitulo.setText("Super Calculadora");

        lblImageCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorAbsoluto)
                            .addComponent(lblRestoDivisao)
                            .addComponent(lblRaizCubica)
                            .addComponent(lblRaizQuadrada)
                            .addComponent(lblElevadoAoCubo))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblInformarValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblRestoDivisaoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addComponent(lblValorAbsolutoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRaizCubicaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRaizQuadradaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblElevadoAoCuboResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImageCalculadora)
                    .addComponent(btnCalcular))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInformarValor))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImageCalculadora)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRestoDivisao)
                            .addComponent(lblRestoDivisaoResultado))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblElevadoAoCubo)
                            .addComponent(lblElevadoAoCuboResultado))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRaizQuadrada)
                            .addComponent(lblRaizQuadradaResultado))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRaizCubica)
                            .addComponent(lblRaizCubicaResultado))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorAbsoluto)
                            .addComponent(lblValorAbsolutoResultado))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        /* Função que calcula:
            - Divisão de um número por dois
            - A potência de expoente 3
            - Raiz quadrada
            - Raiz cubica
            - Valor absoluto
        */
        
        int valor = Integer.parseInt(txtValor.getValue().toString());
        
        int restoDivisao = valor % 2;
        double elevadoAoCubo = Math.pow(valor, 3);
        double raizQuadrada = Math.sqrt(valor);
        double raizCubica = Math.cbrt(valor);
        int valorAbsoluto = Math.abs(valor);
        
        // Verifica se o resultado do calculo da raiz quadrada retornou o valor NaN, 
        // se sim, atribui zero a váriavel. 
        if (Double.isNaN(raizQuadrada)) {
            raizQuadrada = 0;
        }
        
        // Seta os resultados nos labels
        lblRestoDivisaoResultado.setText(String.format("%d", restoDivisao));
        lblElevadoAoCuboResultado.setText(String.format("%.2f", elevadoAoCubo).replace(".", ","));
        lblRaizQuadradaResultado.setText(String.format("%.2f", raizQuadrada).replace(".", ","));
        lblRaizCubicaResultado.setText(String.format("%.2f", raizCubica).replace(".", ","));
        lblValorAbsolutoResultado.setText(String.valueOf(valorAbsoluto));
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperComputador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblElevadoAoCubo;
    private javax.swing.JLabel lblElevadoAoCuboResultado;
    private javax.swing.JLabel lblImageCalculadora;
    private javax.swing.JLabel lblInformarValor;
    private javax.swing.JLabel lblRaizCubica;
    private javax.swing.JLabel lblRaizCubicaResultado;
    private javax.swing.JLabel lblRaizQuadrada;
    private javax.swing.JLabel lblRaizQuadradaResultado;
    private javax.swing.JLabel lblRestoDivisao;
    private javax.swing.JLabel lblRestoDivisaoResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorAbsoluto;
    private javax.swing.JLabel lblValorAbsolutoResultado;
    private javax.swing.JSpinner txtValor;
    // End of variables declaration//GEN-END:variables
}
