/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author rafael
 */
public class Fatorial extends javax.swing.JFrame {
    private int valor;

    /**
     * Creates new form Fatorial
     */
    public Fatorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnValorParaCalculoFatorial = new javax.swing.JSpinner();
        btnCalculaFatorial = new javax.swing.JButton();
        lblResultadoFatorial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCalculaFatorial.setText("Calcular");
        btnCalculaFatorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaFatorialActionPerformed(evt);
            }
        });

        lblResultadoFatorial.setText("Fórmula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnValorParaCalculoFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadoFatorial))
                .addGap(59, 59, 59)
                .addComponent(btnCalculaFatorial)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalculaFatorial)
                    .addComponent(spnValorParaCalculoFatorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lblResultadoFatorial)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculaFatorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaFatorialActionPerformed
        int valor = Integer.parseInt(spnValorParaCalculoFatorial.getValue().toString());
        this.setValor(valor);
        int fatorial = this.getFatorial();
        String formula = this.getFormula();
        
        String resultado = String.format("%s = %d", formula, fatorial);
        lblResultadoFatorial.setText(resultado);
    }//GEN-LAST:event_btnCalculaFatorialActionPerformed

    public void setValor(int n) {
        this.valor = n;
    }
    
    public int getFatorial() {
        // Calcula o fatorial
        int fatorial = 1;
        
        for (int i = 1; i <= this.valor; i++) {
            fatorial = fatorial * i;
        }
        return fatorial;
    }
    
    public String getFormula() {
        // Gera a fórmula fatorial de um número
        String formulaFatorial = String.valueOf(this.valor);
        
        for (int i = this.valor - 1; i > 0; i--) {
            formulaFatorial = formulaFatorial + String.format(" x %d", i);
        }
        return formulaFatorial;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fatorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculaFatorial;
    private javax.swing.JLabel lblResultadoFatorial;
    private javax.swing.JSpinner spnValorParaCalculoFatorial;
    // End of variables declaration//GEN-END:variables
}
