/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.util.Arrays;
import javax.swing.DefaultListModel;
    
/**
 *
 * @author rafael
 */
public class Vetor extends javax.swing.JFrame {
    int vetor[] = new int[10];
    DefaultListModel lista = new DefaultListModel();
    
    /**
     * Creates new form Vetor
     */
    public Vetor() {
        
        initComponents();
        showValoresJList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrTextArea = new javax.swing.JScrollPane();
        lstValoresVetor = new javax.swing.JList<>();
        spnValor = new javax.swing.JSpinner();
        btnAdicionarValor = new javax.swing.JButton();
        btnRemoverValor = new javax.swing.JButton();
        btnOrdenarValor = new javax.swing.JButton();
        lblVetor = new javax.swing.JLabel();
        lblVetorIndexSelecionado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstValoresVetor.setModel(lista);
        lstValoresVetor.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstValoresVetorValueChanged(evt);
            }
        });
        scrTextArea.setViewportView(lstValoresVetor);
        lstValoresVetor.getAccessibleContext().setAccessibleName("");

        btnAdicionarValor.setText("Adicionar");
        btnAdicionarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarValorActionPerformed(evt);
            }
        });

        btnRemoverValor.setText("Remover");
        btnRemoverValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverValorActionPerformed(evt);
            }
        });

        btnOrdenarValor.setText("Ordenar");
        btnOrdenarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarValorActionPerformed(evt);
            }
        });

        lblVetor.setText("Vetor");

        lblVetorIndexSelecionado.setText("[0]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverValor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnOrdenarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVetorIndexSelecionado)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverValor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrdenarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVetor)
                            .addComponent(lblVetorIndexSelecionado))
                        .addGap(18, 18, 18)
                        .addComponent(scrTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Atualiza os valores mostrados no JList.
    private void showValoresJList() {
        lista.clear();
        for (int i = 0; i < 10; i++) {
            lista.add(i, String.format("[%d] -> %d", i, vetor[i]));
        }
    }
    
    // Adiciona um valor a posição seleciona e executa a função que atualiza os valores do JList.
    private void btnAdicionarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarValorActionPerformed
        int valor = (int) spnValor.getValue();
        
        int indiceSelecionado = lstValoresVetor.getSelectedIndex();
        System.out.println(indiceSelecionado);
        if (indiceSelecionado != -1) {
            vetor[indiceSelecionado] = valor;
            showValoresJList();
        }
    }//GEN-LAST:event_btnAdicionarValorActionPerformed
    
    // Remove um valor selecionado e executa a função que atualiza os valores do JList.
    private void btnRemoverValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverValorActionPerformed
        int indiceSelecionado = lstValoresVetor.getSelectedIndex();
        
        if (indiceSelecionado != -1) {
            vetor[indiceSelecionado] = 0;
            showValoresJList();
        }
    }//GEN-LAST:event_btnRemoverValorActionPerformed

    // Ordena os valores do vetor e executa a função que atualiza os valores do JList.
    private void btnOrdenarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarValorActionPerformed
        Arrays.sort(vetor);
        showValoresJList();
    }//GEN-LAST:event_btnOrdenarValorActionPerformed
    
    // Mostra qual o indice o usuário selecionou no JList.
    private void lstValoresVetorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstValoresVetorValueChanged
        int indiceSelecionado = lstValoresVetor.getSelectedIndex();
        
        if (indiceSelecionado != -1) {
            lblVetorIndexSelecionado.setText(String.format("[%d]", indiceSelecionado));
        }
        else {
            lblVetorIndexSelecionado.setText("[0]");
        }
    }//GEN-LAST:event_lstValoresVetorValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vetor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vetor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarValor;
    private javax.swing.JButton btnOrdenarValor;
    private javax.swing.JButton btnRemoverValor;
    private javax.swing.JLabel lblVetor;
    private javax.swing.JLabel lblVetorIndexSelecionado;
    private javax.swing.JList<String> lstValoresVetor;
    private javax.swing.JScrollPane scrTextArea;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
